/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupoAD.appconcurso;

import grupoAD.appconcurso.modelos.Usuario;
import grupoAD.appconcurso.utils.GestorMariadb;
import java.time.LocalDate;

/**
 *
 * @author usuario
 */
public class LogIn extends javax.swing.JDialog
{
    GestorMariadb ges=new GestorMariadb();
    /**
     * Creates new form Login
     */
    public LogIn(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.Panel1.setVisible(true);
        this.Panel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Panel1 = new javax.swing.JPanel();
        LblUsuario = new javax.swing.JLabel();
        LblContraseña = new javax.swing.JLabel();
        TfiUsuario = new javax.swing.JTextField();
        BtnLogIn = new javax.swing.JButton();
        BtnRegistrarse = new javax.swing.JButton();
        TfiContraseña = new javax.swing.JTextField();
        LblError = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblApellidos = new javax.swing.JLabel();
        LblFechaNacimiento = new javax.swing.JLabel();
        LblUsuarioRegistro = new javax.swing.JLabel();
        LblContraseñaRegistro = new javax.swing.JLabel();
        TfiApellidos = new javax.swing.JTextField();
        TfiUsuarioRegistro = new javax.swing.JTextField();
        TfiNombre = new javax.swing.JTextField();
        TfiFechaNacimiento = new javax.swing.JTextField();
        TfiContraseñaRegistro = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();
        LblErrorRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblUsuario.setText("Usuario");

        LblContraseña.setText("Contraseña");

        BtnLogIn.setText("Log in");
        BtnLogIn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnLogInActionPerformed(evt);
            }
        });

        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnRegistrarseActionPerformed(evt);
            }
        });

        LblError.setText(" ");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblError, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(BtnRegistrarse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(BtnLogIn))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblUsuario)
                                    .addComponent(LblContraseña))
                                .addGap(40, 40, 40)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfiUsuario)
                                    .addComponent(TfiContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblUsuario)
                    .addComponent(TfiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblContraseña)
                    .addComponent(TfiContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistrarse)
                    .addComponent(BtnLogIn))
                .addGap(54, 54, 54)
                .addComponent(LblError)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel1.setText("Registro");

        LblNombre.setText("Nombre");

        LblApellidos.setText("Apellidos");

        LblFechaNacimiento.setText("Fecha Nacimiento");

        LblUsuarioRegistro.setText("Usuario");

        LblContraseñaRegistro.setText("Contraseña");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnCancelarActionPerformed(evt);
            }
        });

        Confirmar.setText("Conformar");
        Confirmar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConfirmarActionPerformed(evt);
            }
        });

        LblErrorRegistro.setText(" ");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblFechaNacimiento)
                            .addComponent(LblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblUsuarioRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblContraseñaRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TfiApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfiUsuarioRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(TfiNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(TfiFechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfiContraseñaRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(LblErrorRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Confirmar)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre)
                    .addComponent(TfiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblApellidos)
                    .addComponent(TfiApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFechaNacimiento)
                    .addComponent(TfiFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblUsuarioRegistro)
                    .addComponent(TfiUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblContraseñaRegistro)
                    .addComponent(TfiContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(Confirmar)
                    .addComponent(LblErrorRegistro))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogInActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnLogInActionPerformed
    {//GEN-HEADEREND:event_BtnLogInActionPerformed
        Usuario user=ges.logInUsuario(TfiUsuario.getText(), TfiContraseña.getText());
        if(user!=null){
            FrmPrincipal principal=new FrmPrincipal();
            principal.setVisible(true);
            this.setVisible(false);
            
        }else{
            this.LblError.setText("Nombre o Contraseña incorrectas.");
        }
    }//GEN-LAST:event_BtnLogInActionPerformed

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnRegistrarseActionPerformed
    {//GEN-HEADEREND:event_BtnRegistrarseActionPerformed
        this.Panel1.setVisible(false);
        this.Panel2.setVisible(true);
    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCancelarActionPerformed
    {//GEN-HEADEREND:event_BtnCancelarActionPerformed
        this.Panel1.setVisible(true);
        this.Panel2.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmarActionPerformed
    {//GEN-HEADEREND:event_ConfirmarActionPerformed
        if(this.TfiNombre.getText().isEmpty()){
            this.LblErrorRegistro.setText("Es necesario indicar el Nombre");
            this.TfiNombre.requestFocus();
        }else if(this.TfiApellidos.getText().isEmpty()){
            this.LblErrorRegistro.setText("Es necesario indicar los Apellidos");
            this.TfiApellidos.requestFocus();
        }else if(this.TfiFechaNacimiento.getText().isEmpty()){
            this.LblErrorRegistro.setText("Es necesario indicar la Fecha");
            this.TfiFechaNacimiento.requestFocus();
        }else if(this.TfiUsuarioRegistro.getText().isEmpty()){
            this.LblErrorRegistro.setText("Es necesario indicar el Usuario");
            this.TfiUsuarioRegistro.requestFocus();
        }else if(this.TfiContraseñaRegistro.getText().isEmpty()){
            this.LblErrorRegistro.setText("Es necesario indicar la Contraseña");
            this.TfiContraseñaRegistro.requestFocus();
        }else{
            //trasnformar el string a LocalDate
            LocalDate fechaNacimiento;
            
            //llamar al metodo de registrar nuevos usuarios
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                LogIn dialog = new LogIn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel LblApellidos;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JLabel LblContraseñaRegistro;
    private javax.swing.JLabel LblError;
    private javax.swing.JLabel LblErrorRegistro;
    private javax.swing.JLabel LblFechaNacimiento;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JLabel LblUsuarioRegistro;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JTextField TfiApellidos;
    private javax.swing.JTextField TfiContraseña;
    private javax.swing.JTextField TfiContraseñaRegistro;
    private javax.swing.JTextField TfiFechaNacimiento;
    private javax.swing.JTextField TfiNombre;
    private javax.swing.JTextField TfiUsuario;
    private javax.swing.JTextField TfiUsuarioRegistro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
